version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: ticket-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ticket_db
      MYSQL_ROOT_PASSWORD: password

  redis:
    image: redis:latest
    container_name: ticket-redis
    ports:
      - "6379:6379"

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: ticket-zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    container_name: ticket-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "reservation-success:1:1"
    depends_on:
      - zookeeper