services:
  # 1. MySQL (메인 저장소)
  mysql:
    image: mysql:8.0
    container_name: ticket-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ticket_db
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./data/mysql:/var/lib/mysql

  # 2. Redis (분산 락 & 대기열)
  redis:
    image: redis:latest
    container_name: ticket-redis
    ports:
      - "6379:6379"

  # 3. Zookeeper (Kafka 관리용)
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  # 4. Kafka (메시지 브로커)
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: ticket-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1